### ISSUE TITLE
"token" modifier doesn't work with ranges

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#221]
For example,

```
hello there
```

With a cursor in the middle of "hello", saying "take token past trap" should select both words, but instead starts from current cursor position rather than expanding to start token.

**Comment by AndreasArvidsson** [comment]
The problem is that we process the range before we process the selection type. ie instead of creating a range between two tokens we create a range between the current selection and the decorated mark and then threat that as token. Moving the processing of compound targets to the end of the chain should should solve this.
