### ISSUE TITLE
Modifier that allows you to put cursor on column in every row between two targets

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#345]
```
foo bar
baz bongo
hey world
```

could say "take column from bat to whale" to put cursors before each second word

**Comment by AndreasArvidsson** [comment]
There is two (obvious) way to implement this as I see it
1. Do what vscode does with its add cursor to above/below line and just use column/character index
2. Leverage our tokenizer and count tokens from the left

In the above example number 2 sounds like a good match because it will work if the words on the first column has different length.

How should we handle if the start and end tokens don't line up? eg from `foo` to `word`. The first target could determine column and start row and the end target only determines end row?
