### ISSUE TITLE
Support duplication of lines

### ISSUE THREAD

**Issue by AndreasArvidsson** [pokey/cursorless-vscode#55]
With an option to keep original cursor or not

`dupe line`
Creates a new line with the same selection as previous line. Original line has lost its selection.

`dupe line and stay`
Creates a new line with the same selection as previous line. Original line has kept its selection.

**Comment by pokey** [comment]
I think we should prob support arbitrary targets here, eg "dupe funk", "dupe funk fine", etc.  I think the behaviour should be that the new selection in your "stay" version should be the mark.  That way you could say "take air and bat" referring to two tokens in a function, then "dupe funk", and the new function would have the corresponding tokens "air" and "bat" from the original function selected for easy command chaining.

To make that work, we'd need to make sure that cursorless:
- is smart about merging identical targets, and
- can pass the mark through to the action if requested (today actions just see the final range rather than the original mark)

We'd also probably want to support duplication upwards.  In fact I think I might opt for upward / downward duplication being the options rather than "dupe line" vs "duple line and stay".  I think the distinction you want is whether new thing goes above or below rather than whether you keep selection.  This way you can clone upward in a way that changes the selection if you want to

**Comment by pokey** [comment]
I think could also support syntax `"dupe T taking T[]"`, which would leave the second set of targets selected in the new text.   

Could also support `"dupe T with holes T[]"`, which would insert the text as a snippet with the given holes that can be used as tabstops.  Would basically be syntactic sugar for "insert snippet snipify T with holes T[] after T"

**Comment by AndreasArvidsson** [comment]
You're completely right about the upwards vs downwards. Now we just have to figure out the naming schemes. I was thinking `copyLinesUp` and `copyLinesDown` for the extension side actions but I'm on sure of which one is which actually :D
Is copy down the one that inserts the text below and you keep your selection above. Or is copy down the one that inserts the text above and you have your selection below.
Is only really a question about semantics. Does the up and down in the name indicate where you insert the text or where you keep your selection?
