### ISSUE TITLE
fold/unfold requires funk modifier

### ISSUE THREAD

**Issue by AndreasArvidsson** [pokey/cursorless-vscode#72]
None of these work:
`fold air`
`fold this`

You have to say:
`folk funk air`
`fold funk`

**Comment by pokey** [comment]
Yes this one is to work around the fact that when you say eg "fold every entry" on a map, if one of the entries is a single line, and you ask VSCode to fold it, VSCode will end up folding the entire map. Thus, cursorless will refuse to fold a single-line target to avoid this scenario. 

We could either:
- see if VSCode has an api to determine if a target is the first line of a fold and use that to determine whether to fold
- Try to fold a single-line target anyway if there is only one target
- Special case the "every" modifier, because that's the only place I've hit this issue
